### ISSUE TITLE
User not created during docker container start

### ISSUE THREAD

**Issue by mikebrules** [tutumcloud/tutum-docker-mysql#57]
Hello, following the instructions in the README for creating dbserver with underlying docker volume i.e. this section;

"Mounting the database file volume from other containers"

This all works well (thanks), but the issue is that I never see the generated user and password, and I don't have any grants to allow access, so my linked container can never use the database (TCP connection is fine, the error is "ER_ACCESS_DENIED_ERROR: Access denied for user").

Root with no password within the dbserver container is fine. I expect to see the section in the logs you describe

"You will see an output like the following:...."

But I never see it - is this because my volume exists (not sure why this would be the case). 

To reproduce, follow the "Mounting the database file volume from other containers" and see if you can find the user/pass in the logs...

Thanks

**Comment by tifayuki** [comment]
If the volume container is empty, `tutum/mysql` will try to create a new mysql volume, and therefore you can see the username and password in the logs. Otherwise, if the volume container has contained a mysql volume, `tutum/mysql` will merely use the volume data and skip creating username and password. In this case, you cannot find the prompted username and password in the log. However, you can still connect to mysql with the username and password that is set in the volume container.

To your case, did you remove the volume container named `db_vol` when following the README? For the first time you follow the README, `tutum/mysql` will surely create a username and password ( the log starts with `=> An empty or uninitialized MySQL volume is detected in /var/lib/mysql`). The second time you run mysql, without remove the volume container, the log should start with `=> Using an existing volume of MySQL`

Hope this can help you.

**Comment by mikebrules** [comment]
Thanks tifayuki - I expect that when I followed it the first time I didn;t look in the logs to see the user/pass, and so after the volume was attached I no longer saw it. That would make sense. Thanks for coming back.
